config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :home

  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :accounts, only: [:new, :create, :edit, :update]

  resources :users do
    member do
      post :activate
      post :deactivate
    end
  end

  resources :brands do
    resources :models
  end

  resources :programs

  resources :devices do
    collection do
      get :models_for_select_brand
    end
    member do
      get :assign
      post :save_assign
      get :deassign
      post :save_deassign
    end
    resources :issues do
      resources :trackings, only: [:new, :create]
    end
  end

end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :account
  belongs_to :model, optional: true
  belongs_to :brand, optional: true

  has_many :devices_users_relations, dependent: :destroy
  has_many :users, through: :devices_users_relations
  has_many :issues

  has_and_belongs_to_many :programs

  #########################################
  # VALIDACIÓNS                           #
  #########################################
  validates_presence_of :description

  validates_uniqueness_of :code, if: -> { code.present? }, :scope => [:account]
  validates_uniqueness_of :description, :scope => [:account]

  validate :device_assigned_to_only_one_user_at_the_same_time

  #########################################
  # MËTODOS DE INSTANCIA                  #
  #########################################
  def display_name
    if code.present?
      "#{code} - #{description}"
    else
      description
    end
  end

  def associate_user(user, date = Date.today)
    self.devices_users_relations.build(
      :assignment_date => date,
      :user => user
    ).save
  end

  def deassociate_user(user, date = Date.today)
    user_relation = self.devices_users_relations.detect{|dur| dur.active? && dur.user.id == user.id }
    (user_relation.present? ? user_relation.update_attributes(:deassignment_date => date) : false )
  end

  def current_user
    self.devices_users_relations.detect{|x| x.active? }.try(:user)
  end

  def current_assignment_date
    self.devices_users_relations.detect{|x| x.active? }.try(:assignment_date)
  end

  def assigned?
    current_user.present?
  end

  def category_name_translated
    I18n.t("global_constants.categories.#{category}") if category
  end

  #########################################
  # MËTODOS DE CLASE                      #
  #########################################
  def self.next_code_to_device(acc)
    (acc.devices.any? && acc.devices.map(&:code).max != "" ? acc.devices.map(&:code).max.succ : "0001")
  end

  #########################################
  # MËTODOS PRIVADOS                      #
  #########################################
  private
  def device_assigned_to_only_one_user_at_the_same_time
    if devices_users_relations.select{|dur| dur.active? }.count > 1
      errors.add(:devices_users_relations, :invalid, message: I18n.t('errors.device_assigned_to_user'))
    end
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  include SessionsModule

  def index
    @devices = acc.devices
  end

  def show
    @device = acc.devices.find(params[:id])
  end

  def new
    @device = acc.devices.build
  end

  def create
    @device = acc.devices.build(devices_params)
    unless @device.code.present?
      @device.code = Device.next_code_to_device(@device.account)
    end
    if @device.save
      redirect_to @device
    else
      render 'new'
    end
  end

  def models_for_select_brand
    @brand = acc.brands.find(params[:brand_id])
    @models = @brand.models
    respond_to do |format|
      format.json { render json: @models }
    end
  end

  def edit
    @device = acc.devices.find(params[:id])
  end

  def update
    @device = acc.devices.find(params[:id])
    respond_to do |format|
      if @device.update(devices_params)
        format.html { redirect_to @device }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @device = acc.devices.find(params[:id])
    @device.trash!
    redirect_to devices_path
  end

  def assign
    @device = acc.devices.find(params[:id])
  end

  def save_assign
    @device = acc.devices.find(params[:device_id])
    date = Date.parse(params[:date])
    user = acc.users.actives.find(params[:user_id])
    respond_to do |format|
      if @device.associate_user(user, date)
        flash[:success] = I18n.t('devices.assign_to_user_success')
        format.html { redirect_to @device }
      else
        flash[:error] = I18n.t('devices.assign_to_user_error')
        format.html { render :assign }
      end
    end
  end

  def deassign
    @device = acc.devices.find(params[:id])
  end

  def save_deassign
    @device = acc.devices.find(params[:device_id])
    date = Date.parse(params[:date])
    user = acc.users.actives.find(params[:user_id])
    respond_to do |format|
      if @device.deassociate_user(user, date)
        flash[:success] = I18n.t('devices.deassign_to_user_success')
        format.html { redirect_to @device }
      else
        flash[:error] = I18n.t('devices.deassign_to_user_error')
        format.html { render :deassign }
      end
    end
  end

  private
  def devices_params
    params.require(:device).permit(:description, :observations, :serial_number, 
      :code, :category, :price, :purchase_date, :model_id, :brand_id)
  end
end

app/views/devices/_devices_users_relations.html.erb
<div class="container pt-4">
  <h2><%= t('devices.devices_users_relations') %></h2>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= DevicesUsersRelation.human_attribute_name('user') %></th>
        <th><%= DevicesUsersRelation.human_attribute_name('assignment_date') %></th>
        <th><%= DevicesUsersRelation.human_attribute_name('deassignment_date') %></th>
      </tr>
    </thead>
    <tbody>
      <% @device.devices_users_relations.sort_by{|dur| dur.assignment_date}.each do |relation| %>
        <tr>
          <td><%= relation.user.display_name %></td>
          <td><%= relation.assignment_date.strftime('%d/%m/%Y') %></td>
          <td><%= relation.deassignment_date.try(:strftime, '%d/%m/%Y') %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/devices/_form.html.erb
<div class="pt-4">
  <%= form_for @device do |f| %>
    <!-- Mostrar erros -->
    <%= render 'common/show_errors', :object => @device %>
    <!-- Formulario -->
    <div class="h-100 justify-content-center align-items-center">
      <div class="row">
        <!-- Columna 1 -->
        <div class="col-md">
          <div class="form-group">
            <%= f.label :code %><br>
            <%= f.text_field :code, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description %><br>
            <%= f.text_field :description, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :brand_id %><br>
            <%= f.select("brand_id", acc.brands.map {|b| [ b.description, b.id ] }, {:include_blank => true}, {:class => 'form-control'} ) %>
          </div>
          <div class="form-group">
            <%= f.label :model_id %><br>
            <%= f.select("model_id", (@device && @device.brand ? @device.brand.models.map {|m| [ m.description, m.id ] } : []), {:include_blank => true}, { :class => 'form-control'} ) %>
          </div>
        </div>
        <!-- Columna 2 -->
        <div class="col-md">
          <div class="form-group">
            <%= f.label :serial_number %><br>
            <%= f.text_field :serial_number, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :price %><br>
            <%= f.number_field :price, step: :any, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :purchase_date %><br>
            <%= f.date_field :purchase_date, as: :date, value: f.object.try(:strftime,"%d/%m/%Y"), class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :category %><br>
            <%= f.select("category", CATEGORIES.collect {|c,v| [ t("global_constants.categories.#{v}"), c ] }, {}, { :class => 'form-control' } ) %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :observations %><br>
        <%= f.text_area :observations, step: :any, class: 'form-control' %>
      </div>
      <div class="form-group">
        <div class="mx-auto" style="width: 75px;">
          <%= submit_tag t('actions.save'), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/devices/assign.html.erb
<div class="container h-100 mt-5">
  <div class="row">
    <div class="col-9">
      <!-- Formulario -->
      <h1 class="text-left"><%= @device.display_name %></h1>
      <!-- Mostrar erros -->
      <%= form_tag save_assign_device_path do |form|  %>
        <%= hidden_field_tag("device_id", @device.id) %>
        <div class="form-group">
          <%= label_tag 'date', t('devices.assign_user') %>
          <%= select_tag("user_id", options_from_collection_for_select(acc.users.actives, "id", "display_name"), {:class => 'form-control'} ) %>
        </div>
        <div class="form-group">
          <%= label_tag 'date', t('devices.assign_date') %>
          <%= date_field_tag("date", Date.today, {:class => 'form-control'} ) %>
        </div>
        <div class="form-group">
          <div class="mx-auto" style="width: 75px;">
            <%= submit_tag t('actions.save'), class: 'btn btn-primary' %>
          </div>
        </div>
      <%end%>
      <!-- Fin formulario -->
    </div>
    <div class="col-3">
      <!-- Menú lateral -->
      <%= go_back_link(device_path(@device)) %>
      <!-- Fin menú lateral -->
    </div>
  </div>
</div>

app/views/devices/deassign.html.erb
<div class="container h-100 mt-5">
  <div class="row">
    <div class="col-9">
      <!-- Formulario -->
      <h1 class="text-left"><%= @device.display_name %></h1>
      <!-- Mostrar erros -->
      <%= form_tag save_deassign_device_path do |form|  %>
        <%= hidden_field_tag("device_id", @device.id) %>
        <%= hidden_field_tag("user_id", @device.reload.current_user.id) %>
        <div>
          <dl>
            <dt><%= t('devices.current_user') %></dt>
            <dd><%= @device.current_user.display_name %></dd>
          </dl>
        </div>
        <div class="form-group">
          <%= label_tag 'date', t('devices.deassign_date') %>
          <%= date_field_tag("date", Date.today, {:class => 'form-control'} ) %>
        </div>
        <div class="form-group">
          <div class="mx-auto" style="width: 75px;">
            <%= submit_tag t('actions.save'), class: 'btn btn-primary' %>
          </div>
        </div>
      <%end%>
      <!-- Fin formulario -->
    </div>
    <div class="col-3">
      <!-- Menú lateral -->
      <%= go_back_link(device_path(@device)) %>
      <!-- Fin menú lateral -->
    </div>
  </div>
</div>

app/views/devices/edit.html.erb
<div class="container h-100 mt-5">
  <div class="row">
    <div class="col-9">
      <!-- Formulario -->
      <h1 class="text-left"><%= @device.display_name %></h1>
      <%= render 'form' %>
      <!-- Fin formulario -->
    </div>
    <div class="col-3">
      <!-- Menú lateral -->
      <%= go_back_link(device_path(@device)) %>
      <!-- Fin menú lateral -->
    </div>
  </div>
</div>

app/views/devices/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <!-- Listado dispositivo -->
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col"><%= Device.human_attribute_name('code') %></th>
            <th scope="col"><%= Device.human_attribute_name('description') %></th>
            <th scope="col"><%= Device.human_attribute_name('category') %></th>
            <th scope="col"><%= t('devices.assigned') %></th>
          </tr>
        </thead>
        <tbody>
          <% @devices.each do |device| %>
            <tr>
              <td><%= link_to device.code, device %></td>
              <td><%= link_to device.description, device %></td>
              <td><%= link_to device.category_name_translated, device %></td>
              <td><%=(device.assigned? ? material_icon.done : material_icon.clear )%></td>
            </tr>
          <%end%>
        </tbody>
      </table>
       <!-- Fin listado dispositivo -->
    </div>
    <div class="col-3">
      <!-- Menú lateral -->
      <div class="mx-auto" style="width: 82px;">
        <%= button_to t('actions.new'), new_device_path, method: :get, class: 'btn btn-primary' %>
      </div>
      <!-- Fin menú lateral -->
    </div>
  </div>
</div>

app/views/devices/new.html.erb
<div class="container h-100 mt-5">
  <div class="row">
    <div class="col-9">
      <!-- Formulario -->
      <h1 class="text-left"><%= t('devices.new') %></h1>
      <%= render 'form' %>
      <!-- Fin formulario -->
    </div>
    <div class="col-3">
      <!-- Menú lateral -->
      <%= go_back_link(devices_path) %>
      <!-- Fin menú lateral -->
    </div>
  </div>
</div>

app/views/devices/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <!-- Datos -->
      <h1><%= @device.display_name %></h1>
      <div class="container">
        <div class="row">
          <div class="col-6">
            <!-- Columna de datos 1 -->
            <dl>
              <dt><%= Device.human_attribute_name('code') %></dt>
              <dd><%= @device.code %></dd>
            </dl>
            <dl>
              <dt><%= Device.human_attribute_name('description') %></dt>
              <dd><%= @device.description %></dd>
            </dl>
            <dl>
              <dt><%= Device.human_attribute_name('serial_number') %></dt>
              <dd><%= @device.serial_number %></dd>
            </dl>
            <dl>
              <dt><%= Device.human_attribute_name('category') %></dt>
              <dd><%= @device.category_name_translated %></dd>
            </dl>
            <% if @device.assigned? %>
              <dl>
                <dt><%= t('devices.current_user') %></dt>
                <dd><%= @device.current_user.display_name %></dd>
              </dl>
            <%end%>
          </div>
          <div class="col-6">
            <!-- Columna de datos 2 -->
            <dl>
              <dt><%= Device.human_attribute_name('brand') %></dt>
              <dd><%= @device.brand.try(:display_name) %></dd>
            </dl>
            <dl>
              <dt><%= Device.human_attribute_name('model') %></dt>
              <dd><%= @device.model.try(:display_name) %></dd>
            </dl>
            <% if current_user.admin? || current_user.technician? %>
              <dl>
                <dt><%= Device.human_attribute_name('price') %></dt>
                <dd><%= @device.price %></dd>
              </dl>
              <dl>
                <dt><%= Device.human_attribute_name('purchase_date') %></dt>
                <dd><%= @device.purchase_date.try(:strftime, '%d/%m/%Y') %></dd>
              </dl>
            <%end%>
          </div>
        </div>
      </div>
      <% if current_user.admin? || current_user.technician? %>
        <dl>
          <dt><%= Device.human_attribute_name('observations') %></dt>
          <dd><%= @device.observations %></dd>
        </dl>
      <%end%>
      <!-- Fin datos -->
      <!-- Listado de issues -->
      <% if @device.issues.any? %>
        <%= render "issues/issues", :issues => ((current_user.admin? || current_user.technician?) ? @device.issues : @device.issues.for_user(current_user)) %>
      <%end%>
      <!-- Fin de listado de issues -->
      <!-- Listado histórico de usuarios -->
      <% if (current_user.admin? || current_user.technician?) && @device.devices_users_relations.any? %>
        <%= render 'devices_users_relations' %>
      <%end%>
      <!-- Fin listado histórico de usuarios -->
    </div>
    <div class="col-3">
      <!-- Menú lateral -->
      <div class="mx-auto">
        <%= go_back_link(current_user_can?(controller_name, "index") ? devices_path : home_index_path) %>
        <% if current_user_can?(controller_name, "edit") %>
          <hr>
          <%= button_to t('actions.edit'), edit_device_path, method: :get, class: 'btn btn-primary' %>
        <%end%>
        <% if current_user_can?(controller_name, "edit") %>
          <br />
          <%= button_to t('actions.delete'), device_path, method: :delete, class: 'btn btn-primary', data: {confirm: t('actions.confirm_question')} %>
        <%end%>
        <% if current_user_can?(controller_name, "assign") && current_user_can?(controller_name, "deassign") %>
          <hr>
          <% if @device.assigned? %>
            <%= button_to t('devices.deassign_to_user'), deassign_device_path, method: :get, class: 'btn btn-primary' %>
          <%else%>
            <%= button_to t('devices.assign_to_user'), assign_device_path, method: :get, class: 'btn btn-primary' %>
          <%end%>
        <%end%>
        <% if current_user_can?("issues", "new") %>
          <hr>
          <%= button_to t('issues.create_issue'),  new_device_issue_path(@device), method: :get, class: 'btn btn-primary' %>
        <%end%>
      </div>
      <!-- Fin menú lateral -->
    </div>
  </div>
</div>