config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :home

  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :accounts, only: [:new, :create, :edit, :update]

  resources :users do
    member do
      post :activate
      post :deactivate
    end
  end

  resources :brands do
    resources :models
  end

  resources :programs

  resources :devices do
    collection do
      get :models_for_select_brand
    end
    member do
      get :assign
      post :save_assign
      get :deassign
      post :save_deassign
    end
    resources :issues do
      resources :trackings, only: [:new, :create]
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :account

  has_many :devices_users_relations, dependent: :destroy
  has_many :devices, through: :devices_users_relations
  has_many :issues
  has_many :trackings

  #########################################
  # SCOPES                                #
  #########################################
  scope :actives, -> { where("active IS TRUE") }

  #########################################
  # VALIDACIÓNS                           #
  #########################################
  has_secure_password :password, validations: false

  validates_presence_of :login, :password_digest, :name, :surname_1, :email, :rol
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates_uniqueness_of :email, :login, case_sensitive: true
  validates :rol, inclusion: ROLES.values
  validates :locale, inclusion: I18n.available_locales.map(&:to_s)

  #########################################
  # CALLBACKS                             #
  #########################################
  before_create do |user|
    user.active ||= true
    user.locale ||= AVAILABLE_LOCALES[:es_ES]
  end

  #########################################
  # MËTODOS DE INSTANCIA                  #
  #########################################
  def active_devices
    devices_users_relations.select{|x| x.active? }.map(&:device)
  end

  def display_name
    "#{login} - #{full_name}"
  end

  def full_name
    [name, surname_1, surname_2].join(" ")
  end

  def admin?
    rol == ROLES[:admin]
  end

  def technician?
    rol == ROLES[:technician]
  end
  
  def basic?
    rol == ROLES[:basic]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsModule

  def index
    @users = acc.users
  end

  def show
    @user = acc.users.find(params[:id])
  end

  def new
    @user = acc.users.new
  end

  def create
    @user = acc.users.build(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = acc.users.find(params[:id])
  end

  def update
    @user = acc.users.find(params[:id])
    if @user.update(user_params)
      if current_user_can?("users", "show")
        redirect_to @user
      else
        flash[:success] = I18n.t('users.success_updated')
        redirect_to home_index_path
      end
    else
      render 'edit'
    end
  end

  def activate
    @user = acc.users.find(params[:id])
    @user.update_attributes! :active => true
    flash[:success] = I18n.t('users.activate')
    redirect_to @user
  end

  def deactivate
    @user = acc.users.find(params[:id])
    @user.update_attributes! :active => false
    flash[:success] = I18n.t('users.deactivate')
    redirect_to @user
  end

  private
  def user_params
    params.require(:user).permit(:login, :email, :password, :name, 
      :surname_1, :surname_2, :id_document_number, :rol, :locale)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="pt-4">
  <%= form_for @user do |f| %>
    <!-- Mostrar erros -->
    <%= render 'common/show_errors', :object => @user %>
    <!-- Formulario -->
    <div class="h-100 justify-content-center align-items-center">
      <div class="row">
        <div class="col-md">
          <div class="form-group">
            <%= f.label :login %><br>
            <%= f.text_field :login, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password %><br>
            <%= f.text_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %><br>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="col-md">
          <div class="form-group">
            <%= f.label :surname_1 %><br>
            <%= f.text_field :surname_1, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :surname_2 %><br>
            <%= f.text_field :surname_2, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :id_document_number %><br>
            <%= f.text_field :id_document_number, class: 'form-control' %>
          </div>
          <% unless @user == current_user && current_user.admin? %>
            <%# Si eres un usuario admin non podes mudar a un rol inferior. Debe facelo outro admin. Así asegurámonos de ter sempre un admin %>
            <div class="form-group">
              <%= f.label :rol %><br>
              <%= f.select("rol", ROLES.collect {|c,v| [ t("global_constants.roles.#{v}"), c ] }, {}, { :class => 'form-control' } ) %>
            </div>
          <%end%>
          <div class="form-group">
            <%= f.label :locale %><br>
            <%= f.select("locale", AVAILABLE_LOCALES.collect {|c,v| [ t("global_constants.available_locales.#{v}"), v ] }, {}, { :class => 'form-control' } ) %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="mx-auto" style="width: 75px;">
          <%= submit_tag t('actions.save'), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_form_my_user.html.erb
<div class="pt-4">
  <%= form_for @user do |f| %>
    <!-- Mostrar erros -->
    <%= render 'common/show_errors', :object => @user %>
    <!-- Formulario -->
    <div class="h-100 justify-content-center align-items-center">
      <div class="row">
        <div class="col-md">
          <div class="form-group">
            <dt><%= User.human_attribute_name('login') %></dt>
            <dd><%= @user.login %></dd>
          </div>
          <div class="form-group">
            <%= f.label :email %><br>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password %><br>
            <%= f.text_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="col-md">
          <div class="form-group">
            <%= f.label :surname_1 %><br>
            <%= f.text_field :surname_1, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :surname_2 %><br>
            <%= f.text_field :surname_2, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :id_document_number %><br>
            <%= f.text_field :id_document_number, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :locale %><br>
            <%= f.select("locale", AVAILABLE_LOCALES.collect {|c,v| [ t("global_constants.available_locales.#{v}"), v ] }, {}, { :class => 'form-control' } ) %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="mx-auto" style="width: 75px;">
          <%= submit_tag t('actions.save'), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container h-100 mt-5">
  <div class="row">
    <div class="col-9">
      <!-- Formulario -->
      <h1 class="text-left"><%= @user.full_name %></h1>
      <% if current_user.admin? %>
        <%= render 'form' %>
      <%else%>
        <%= render 'form_my_user' %>
      <%end%>
      <!-- Fin formulario -->
    </div>
    <div class="col-3">
      <!-- Menú lateral -->
      <% if current_user.admin? %>
        <%= go_back_link(user_path(@user)) %>
      <%else%>
        <%= go_back_link(home_index_path) %>
      <%end%>
      <!-- Fin menú lateral -->
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <!-- Listado usuarios -->
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col"><%= User.human_attribute_name('login') %></th>
            <th scope="col"><%= User.human_attribute_name('email') %></th>
            <th scope="col"><%= User.human_attribute_name('name') %></th>
            <th scope="col"><%= User.human_attribute_name('active') %></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.login, user %> </td>
              <td><%= link_to user.email, user %> </td>
              <td><%= link_to user.full_name, user %> </td>
              <td><%=(user.active? ? material_icon.done : material_icon.clear )%></td>
            </tr>
          <%end%>
        </tbody>
      </table>
       <!-- Fin listado usuarios -->
    </div>
    <div class="col-3">
      <!-- Menú lateral -->
      <div class="mx-auto" style="width: 82px;">
        <%= button_to t('actions.new'), new_user_path, method: :get, class: 'btn btn-primary' %>
      </div>
      <!-- Fin menú lateral -->
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container h-100 mt-5">
  <div class="row">
    <div class="col-9">
      <!-- Formulario -->
      <h1 class="text-left"><%= t('users.new') %></h1>
      <%= render 'form' %>
      <!-- Fin formulario -->
    </div>
    <div class="col-3">
      <!-- Menú lateral -->
      <%= go_back_link(users_path) %>
      <!-- Fin menú lateral -->
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <!-- Datos -->
      <h1><%= @user.full_name %></h1>
      <dl>
        <dt><%= User.human_attribute_name('login') %></dt>
        <dd><%= @user.login %></dd>
        <dt><%= User.human_attribute_name('email') %></dt>
        <dd><%= @user.email %></dd>
        <dt><%= User.human_attribute_name('name') %></dt>
        <dd><%= @user.name %></dd>
        <dt><%= User.human_attribute_name('surname_1') %></dt>
        <dd><%= @user.surname_1 %></dd>
        <dt><%= User.human_attribute_name('surname_2') %></dt>
        <dd><%= @user.surname_2 %></dd>
        <dt><%= User.human_attribute_name('id_document_number') %></dt>
        <dd><%= @user.id_document_number %></dd>
        <dt><%= User.human_attribute_name('rol') %></dt>
        <dd><%= t("global_constants.roles.#{@user.rol}") %></dd>
      </dl>
      <!-- Fin datos -->
    </div>
    <div class="col-3">
      <!-- Menú lateral -->
      <div class="mx-auto">
        <%= go_back_link(users_path) %>
        <hr>
        <%= button_to t('actions.edit'), edit_user_path, method: :get, class: 'btn btn-primary' %>
        <br />
        <% unless @user == current_user %>
          <%= button_to (@user.active? ? t('actions.deactivate') : t('actions.activate')), (@user.active? ? deactivate_user_path : activate_user_path), class: 'btn btn-primary' %>
        <%end%>
      </div>
      <!-- Fin menú lateral -->
    </div>
  </div>
</div>