config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :home

  resources :users

  resources :sessions, only: [:new, :create, :destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :accounts, only: [:new, :create, :edit, :update]

  resources :users do
    member do
      post :activate
      post :deactivate
    end
  end

  resources :brands do
    resources :models
  end

  resources :programs

  resources :devices do
    collection do
      get :models_for_select_brand
    end
    member do
      get :assign
      post :save_assign
      get :deassign
      post :save_deassign
    end
    resources :issues do
      resources :trackings, only: [:new, :create]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('common.title') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Menú superior -->
    <div id="top-menu">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <%= nav_link(t('menu.home'), home_index_path) if current_user_can?("home", "index") %>
            <%= nav_link(t('menu.users'), users_path) if current_user_can?("users", "index") %>
            <%= nav_link(t('menu.brands'), brands_path) if current_user_can?("brands", "index") %>
            <%= nav_link(t('menu.programs'), programs_path) if current_user_can?("programs", "index") %>
            <%= nav_link(t('menu.devices'), devices_path) if current_user_can?("devices", "index") %>
          </ul>
          <div class="row justify-content-center pr-3">
            <spam class="text-success"> <%= material_icon.person %> </spam>
            <spam class="text-white"> <%= t('menu.connected_as') %> </spam>
            <spam class="text-white" >&nbsp; <%= current_user.login %> &nbsp;</spam>
            <span class="text-white">(<%= link_to t('menu.logout'), logout_path %>)</span>
          </div>
        </div>
      </nav>
    </div>

    <!-- Contedor principal -->
    <div id="main-container">
      <%= render 'common/show_flash_messages' %>
      <div class="row pt-4">
        <div class="col">
          <!-- Columna libre pola marxe esquerda -->
        </div>
        <div class="col-9">
          <!-- Contido -->
          <%= yield %>
        </div>
        <div class="col">
          <!-- Columna libre pola marxe dereita -->
        </div>
      </div>      
    <div>

    <!-- Footer -->
    <div id="bottom-footer" class="pt-5">
      <!--<footer class="alert alert-light fixed-bottom">-->
      <footer class="alert alert-light">
        <div class="text-center py-3">
          <spam><%= t('common.footer_text') %> </spam>
        </div>
      </footer>
    </div>

  </body>
</html>